# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kirin < Formula
  desc ""
  homepage ""
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thetnaingtn/kirin/releases/download/v0.1.1/kirin_Darwin_x86_64.tar.gz"
      sha256 "3cd2dc5deb1bda1d020fcef925eccd860dabfb49715ebb88dbc79010cbd40021"

      def install
        bin.install "kirin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thetnaingtn/kirin/releases/download/v0.1.1/kirin_Darwin_arm64.tar.gz"
      sha256 "18df0ccdb3be3771eb75f91df27d2fe0cf1e0aa1534bdcbfe521cb945af352ec"

      def install
        bin.install "kirin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/thetnaingtn/kirin/releases/download/v0.1.1/kirin_Linux_x86_64.tar.gz"
      sha256 "b610dd926b91bdff73575d0e1cda39f3f125e216bb71d9c6d9d75e782fbd60ef"
      def install
        bin.install "kirin"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/thetnaingtn/kirin/releases/download/v0.1.1/kirin_Linux_arm64.tar.gz"
      sha256 "74ac332eccee53026d1eba56b0e78b17def91897d5997921b6e307893e55e3f2"
      def install
        bin.install "kirin"
      end
    end
  end

  test do
    system "#{bin}/kirin --version"
  end
end
